### PR TITLE
Add doc strings

### LINKED ISSUE #2: add docstrings

### PR DESCRIPTION
**Pull request by rejuvyesh**
Fixes #2.

### CODE REVIEW

**Comment by zsunberg** [comment]
Jayesh, thanks a bunch for doing this! I was actually thinking that the readme was sufficient documentation for such a small package. Do you and @etotheipluspi think we need the generated documentation? I just think it's easier to access on the readme, and I definitely _don't_ want to have it in two places simultaneously. (We definitely DO need docstrings though)

**Comment by rejuvyesh** [comment]
I was thinking of adding a section (example) about defining a POMDP using `GenerativeModels`. I think proper docs are always better than the README docs. I'll be fine with splitting the commit so that you can merge only the docstrings.

**Comment by etotheipluspi** [comment]
I like @rejuvyesh's idea about adding an example with a generative model to the main docs. It can go in the Defining POMDP section.

**Comment by zsunberg** [comment]
Yeah, adding an example to the main docs is a good idea. @etotheipluspi do you think Generativemodels.jl should have docs generated by Documenter.jl, or is the readme alone sufficient?

**Comment by rejuvyesh** [comment]
BTW I updated the commit to only reflect the docstring changes.

**Comment by zsunberg** [comment]
Thanks

**Pull request merged**
